"use client";
import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { ArrowUpRight, CheckCircle2, Loader2, Plus, RefreshCw, ShieldCheck, Trash2 } from "lucide-react";
import type { FoundationEvent } from "@/lib/models";
import type { CheckoutSession } from "@/lib/razorpay";

type Student = {name:string; class:string; email:string; phone:string; experience:"Beginner"|"Intermediate"|"Experienced"; preferences:string[]};
type Payment = {razorpay_order_id:string; razorpay_payment_id:string; razorpay_signature:string};
type Gateway = {open():void; on(event:string, handler:()=>void):void};
declare global { interface Window { Razorpay?: new (options:Record<string,unknown>)=>Gateway } }
const blank = (count:number): Student => ({name:"", class:"", email:"", phone:"", experience:"Beginner", preferences:Array(count).fill("")});
async function post(path:string, body:unknown) {
  const response = await fetch(path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});
  const data = await response.json();
  if (!response.ok) throw new Error(data.error ?? "Please try again.");
  return data;
}
async function loadRazorpay() {
  if (window.Razorpay) return;
  await new Promise<void>((resolve,reject)=>{const script=document.createElement("script");script.src="https://checkout.razorpay.com/v1/checkout.js";script.onload=()=>resolve();script.onerror=()=>reject(new Error("Checkout could not load. Check your connection and retry."));document.head.appendChild(script);});
}
export function DelegationCheckout({event,ready,refundPolicy}:{event:FoundationEvent;ready:boolean;refundPolicy:string}) {
  const [students,setStudents]=useState<Student[]>([blank(event.preferenceCount),blank(event.preferenceCount)]);
  const [school,setSchool]=useState(""),[teacher,setTeacher]=useState(""),[email,setEmail]=useState(""),[phone,setPhone]=useState("");
  const [accepted,setAccepted]=useState(false),[session,setSession]=useState<CheckoutSession>();
  const [busy,setBusy]=useState(false),[paid,setPaid]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
  const inFlight=useRef(false), requestId=useRef<string>("");
  const key=`valora-delegation:${event.id}`;
  useEffect(()=>{try { const saved=sessionStorage.getItem(key); if(saved){const parsed=JSON.parse(saved);if(parsed.school){if(parsed.session?.token)setSession(parsed.session);setSchool(parsed.school);setTeacher(parsed.teacher);setEmail(parsed.email);setPhone(parsed.phone);setStudents(parsed.students);requestId.current=parsed.requestId;}}}catch{}},[key]);
  function update(index:number, patch:Partial<Student>){setStudents(current=>current.map((s,i)=>i===index?{...s,...patch}:s));}
  async function check(checkout=session){if(!checkout)return false;const result=await post("/api/payments/status",{token:checkout.token});if(result.paid){setPaid(true);setNotice("");return true;}return false;}
  async function open(checkout:CheckoutSession){if(await check(checkout)){setBusy(false);return;}await loadRazorpay();if(!window.Razorpay)throw new Error("Checkout is unavailable. Please retry.");const gateway=new window.Razorpay({key:checkout.key,order_id:checkout.order_id,amount:checkout.amount,currency:checkout.currency,name:"Valora Foundation",description:`School delegation · ${students.length} delegates`,prefill:{name:teacher,email,contact:phone},theme:{color:"#650b25"},modal:{ondismiss:()=>{setBusy(false);inFlight.current=false;setNotice("Your roster is saved in this browser tab. You can resume payment here.");}},handler:async(payment:Payment)=>{setBusy(true);try{await post("/api/payments/verify",{...payment,token:checkout.token});setPaid(true);setNotice("");}catch(e){setError((e as Error).message);setNotice("If you were charged, use Check payment status below.");}finally{setBusy(false);inFlight.current=false;}}});gateway.on("payment.failed",()=>{setBusy(false);inFlight.current=false;setError("Payment did not complete. Retry using the saved checkout.");});gateway.open();}
  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(inFlight.current)return;inFlight.current=true;setBusy(true);setError("");setNotice("");try{if(!requestId.current)requestId.current=crypto.randomUUID();sessionStorage.setItem(key,JSON.stringify({session,school,teacher,email,phone,students,requestId:requestId.current}));const checkout=session??await post("/api/payments/delegation-order",{event_id:event.id,school,teacher_name:teacher,teacher_email:email,teacher_phone:phone,students,accepted_terms:accepted,request_id:requestId.current}) as CheckoutSession;setSession(checkout);sessionStorage.setItem(key,JSON.stringify({session:checkout,school,teacher,email,phone,students,requestId:requestId.current}));await open(checkout);}catch(e){setError((e as Error).message);setBusy(false);inFlight.current=false;}}
  async function refresh(){setBusy(true);setError("");try{if(!await check())setNotice("Payment is still awaiting confirmation. Check again shortly or contact Valora with your reference.");}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  if(paid)return <div className="checkout-success"><CheckCircle2 size={48}/><h2>Delegation payment confirmed.</h2><p>Each student will receive their committee allocation and digital E-ID at their listed email address. Check spam folders too.</p><div className="checkout-reference">Lead registration reference<strong>{session?.registration_id}</strong></div><Link href={`/events/${event.slug}`} className="button button-primary">Conference details <ArrowUpRight size={18}/></Link></div>;
  return <div className="checkout-panel delegation-panel"><div className="checkout-panel-heading"><h2>{session?"Resume your delegation":"School delegation"}</h2><p>Register 2–30 students in one roster and pay the combined fee in a single secure checkout. Each student needs their own email for their E-ID.</p></div>
    {!ready&&<div className="important-note"><ShieldCheck size={22}/><div><h3>Registration opens soon</h3><p>Payments are not open yet. Contact Valora for school registration updates.</p></div></div>}
    <form onSubmit={submit}>
      {!session&&<><div className="delegation-section-title">01 / School and teacher</div><div className="checkout-fields"><label>School name *<input required maxLength={200} value={school} onChange={e=>setSchool(e.target.value)} placeholder="Your school"/></label><label>Teacher / coordinator *<input required maxLength={120} value={teacher} onChange={e=>setTeacher(e.target.value)} placeholder="Full name"/></label><label>Teacher email *<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="teacher@school.edu"/></label><label>Teacher phone *<input required type="tel" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+91"/></label></div>
      <div className="delegation-section-title">02 / Student roster <span>{students.length} delegates</span></div>
      {students.map((student,index)=><div className="delegation-student" key={index}><div className="delegation-student-head"><h3>Student {String(index+1).padStart(2,"0")}</h3><button type="button" aria-label={`Remove student ${index+1}`} disabled={students.length<=2} onClick={()=>setStudents(current=>current.filter((_,i)=>i!==index))}><Trash2 size={16}/> Remove</button></div><div className="checkout-fields"><label>Full name *<input required maxLength={120} value={student.name} onChange={e=>update(index,{name:e.target.value})}/></label><label>Class / grade *<input required maxLength={80} value={student.class} onChange={e=>update(index,{class:e.target.value})}/></label><label>Student email *<input required type="email" value={student.email} onChange={e=>update(index,{email:e.target.value})}/></label><label>Contact number *<input required type="tel" value={student.phone} onChange={e=>update(index,{phone:e.target.value})}/></label><label>MUN experience *<select value={student.experience} onChange={e=>update(index,{experience:e.target.value as Student["experience"]})}><option>Beginner</option><option>Intermediate</option><option>Experienced</option></select></label></div><div className="checkout-preferences"><h3>Committee preferences</h3><div className="checkout-preference-grid">{student.preferences.map((value,i)=><label key={i}>Choice {i+1}<select required value={value} onChange={e=>update(index,{preferences:student.preferences.map((p,n)=>n===i?e.target.value:p)})}><option value="">Select committee</option>{event.categories.map(c=><option key={c.id} value={c.id} disabled={student.preferences.includes(c.id)&&value!==c.id}>{c.name}</option>)}</select></label>)}</div></div></div>)}
      <button className="delegation-add" type="button" disabled={students.length>=30} onClick={()=>setStudents(current=>[...current,blank(event.preferenceCount)])}><Plus size={18}/> Add another student</button>
      <div className="refund-policy"><strong>Cancellations & refunds</strong><p>{refundPolicy||"The organiser will publish the refund policy before opening payments."}</p></div><label className="checkout-consent"><input type="checkbox" required checked={accepted} onChange={e=>setAccepted(e.target.checked)}/><span>I agree to the <Link href="/terms" target="_blank">event terms</Link> and <Link href="/privacy" target="_blank">privacy policy</Link>, including the refund policy above, on behalf of this delegation.</span></label></>}
      {error&&<p className="checkout-error" role="alert">{error}</p>}{notice&&<p className="checkout-notice" role="status">{notice}</p>}
      <button className="button button-primary checkout-pay" type="submit" disabled={!ready||busy}>{busy?<><Loader2 size={18} className="checkout-spinner"/>Please wait…</>:<>{session?"Resume secure payment":`Pay for ${students.length} students · ₹${(event.fee*students.length).toLocaleString("en-IN")}`}<ArrowUpRight size={18}/></>}</button>
      {session&&<><button className="checkout-status" type="button" onClick={refresh} disabled={busy}><RefreshCw size={15}/>Check payment status</button><div className="checkout-reference">Lead registration reference<strong>{session.registration_id}</strong></div></>}
      <span className="checkout-security"><ShieldCheck size={15}/>Secure checkout by Razorpay · UPI, cards & more</span>
    </form></div>;
}
